=== arccode/factory/py/test/test_lists/test_list.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "reference: http://goto/cros-factory-test-list, ./TEST_LIST.md, ./JSON_TEST_LIST.md",
  "definitions": {
    "test_object": {
      "type": ["object", "string"],
      "properties": {
        "action_on_failure": {
          "type": "string",
          "enum": ["NEXT", "PARENT", "STOP"]
        },
        "args":  {"type": "object"},
        "disable_abort": {"type": "boolean"},
        "disable_services": {
          "type": "array",
          "items": {"type": "string"}
        },
        "enable_services": {
          "type": "array",
          "items": {"type": "string"}
        },
        "exclusive_services": {
          "type": "array",
          "items": {"type": "string"}
        },
        "has_ui": {"type": "boolean"},
        "id": {"type": "string"},
        "iterations": {"type": "number"},
        "label": {"type": ["string", "object"]},
        "never_fails": {"type": "boolean"},
        "parallel": {"type": "boolean"},
        "pytest_name": {"type": "string"},
        "retries": {"type": "number"},
        "run_if": {"type": "string"},
        "subtests": {
          "type": "array",
          "items": {"$ref": "#/definitions/test_object"}
        },
        "teardown": {"type": "boolean"},

        "inherit": {
          "type": "string"
        },
        "child_action_on_failure": {
          "type": "string",
          "enum": ["NEXT", "PARENT", "STOP"]
        },
        "__comment": {
          "description": "this field will be completely ignored by test list loader.",
          "type": "string"
        }
      },
      "additionalProperties": false
    },

    "test_options": {
      "type": "object"
    }
  },

  "type": "object",
  "properties": {
    "inherit": {
      "type": "array",
      "items": {"type": "string"}
    },

    "options": {
      "$ref": "#/definitions/test_options"
    },

    "constants": {
      "type": "object"
    },

    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/test_object"
      }
    },

    "tests": {
      "type": "array",
      "items": {"$ref": "#/definitions/test_object"}
    },

    "__comment": {
      "description": "this field will be completely ignored by test list loader",
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== arccode/factory/py/test/test_lists/manager_unittest/a.test_list.json
{
  "inherit": ["base.test_list"],

  "constants": {
    "phase": "EVT",
    "enable_shopfloor": true,
    "component_list": ["cpu", "audio", "flash_chip"],
    "timestamp": 1
  },

  "options": {
    "strict_ids": true,
    "engineering_password_sha1": "dummy_password_sha1",
    "ui_lang": "zh",
    "sync_event_log_period_secs": 0,
    "disable_cros_shortcut_keys": true,
    "core_dump_watchlist": []
  },

  "definitions": {
    "LEDTest": {
      "inherit": "OperatorTest",
      "pytest_name": "led",
      "args": {
        "colors": ["RED", "GREEN", "BLUE"]
      }
    }
  },

  "tests": [
    {
      "id": "SMT",
      "subtests": [
        {
          "inherit": "LEDTest",
          "id": "FirstLEDTest"
        },
        {
          "inherit": "LEDTest",
          "id": "SecondLEDTest",
          "args": {
            "colors": ["RED", "GREEN"]
          }
        },
        {
          "id": "VerifyComponents",
          "pytest_name": "verify_components",
          "args": {
            "component_list": "eval! constants.component_list",
            "skip_shopfloor": "eval! not constants.enable_shopfloor"
          }
        },
        {
          "id": "Halt",
          "inherit": "HaltStep"
        },
        "LEDTest",
        "LEDTest"
      ]
    }
  ]
}
